import { Campaign } from './types';

export const mockCampaigns: Campaign[] = [
  {
    id: 'CAM-001',
    listingName: 'Modern Downtown Loft',
    status: 'active',
    type: 'ppc',
    startDate: new Date('2025-08-20'),
    budget: 500,
    spent: 120.5,
    placements: ['homepage', 'sidebar'],
  },
  {
    id: 'CAM-002',
    listingName: 'Suburban Family Home',
    status: 'paused',
    type: 'ppv',
    startDate: new Date('2025-08-15'),
    budget: 300,
    spent: 250.75,
    placements: ['search_top'],
  },
  {
    id: 'CAM-003',
    listingName: 'Cozy Beachside Cottage',
    status: 'ended',
    type: 'ppc',
    startDate: new Date('2025-07-01'),
    budget: 1000,
    spent: 998.5,
    placements: ['homepage', 'search_top', 'sidebar'],
  },
  {
    id: 'CAM-004',
    listingName: 'Luxury Penthouse with View',
    status: 'active',
    type: 'ppv',
    startDate: new Date('2025-08-25'),
    budget: 800,
    spent: 50,
    placements: ['sidebar'],
  },
  {
    id: 'CAM-005',
    listingName: 'Rural Farmhouse Retreat',
    status: 'active',
    type: 'ppc',
    startDate: new Date('2025-08-18'),
    budget: 250,
    spent: 180.2,
    placements: ['search_top', 'sidebar'],
  },
];
