import { SearchableSelectItem } from './types';

export const ukLocations: SearchableSelectItem[] = [
  { value: 'all', label: 'All Location' },
  { value: 'London', label: 'London' },
  { value: 'Birmingham', label: 'Birmingham' },
  { value: 'Portsmouth', label: 'Portsmouth' },
  { value: 'Southampton', label: 'Southampton' },
  { value: 'Nottingham', label: 'Nottingham' },
  { value: 'Bristol', label: 'Bristol' },
  { value: 'Manchester', label: 'Manchester' },
  { value: 'Liverpool', label: 'Liverpool' },
  { value: 'Leicester', label: 'Leicester' },
  { value: 'Worthing', label: 'Worthing' },
  { value: 'Coventry', label: 'Coventry' },
  { value: 'Belfast', label: 'Belfast' },
  { value: 'Bradford', label: 'Bradford' },
  { value: 'Derby', label: 'Derby' },
  { value: 'Plymouth', label: 'Plymouth' },
  { value: 'Westminster', label: 'Westminster' },
  { value: 'Wolverhampton', label: 'Wolverhampton' },
  { value: 'Northampton', label: 'Northampton' },
  { value: 'Norwich', label: 'Norwich' },
  { value: 'Luton', label: 'Luton' },
  { value: 'Solihull', label: 'Solihull' },
  { value: 'Islington', label: 'Islington' },
  { value: 'Aberdeen', label: 'Aberdeen' },
  { value: 'Croydon', label: 'Croydon' },
  { value: 'Bournemouth', label: 'Bournemouth' },
  { value: 'Basildon', label: 'Basildon' },
  { value: 'Maidstone', label: 'Maidstone' },
  { value: 'Ilford', label: 'Ilford' },
  { value: 'Warrington', label: 'Warrington' },
  { value: 'Oxford', label: 'Oxford' },
  { value: 'Harrow', label: 'Harrow' },
  { value: 'West Bromwich', label: 'West Bromwich' },
  { value: 'Gloucester', label: 'Gloucester' },
  { value: 'York', label: 'York' },
  { value: 'Blackpool', label: 'Blackpool' },
  { value: 'Stockport', label: 'Stockport' },
  { value: 'Sale', label: 'Sale' },
  { value: 'Tottenham', label: 'Tottenham' },
  { value: 'Cambridge', label: 'Cambridge' },
  { value: 'Romford', label: 'Romford' },
  { value: 'Colchester', label: 'Colchester' },
  { value: 'High Wycombe', label: 'High Wycombe' },
  { value: 'Gateshead', label: 'Gateshead' },
  { value: 'Slough', label: 'Slough' },
  { value: 'Blackburn', label: 'Blackburn' },
  { value: 'Chelmsford', label: 'Chelmsford' },
  { value: 'Rochdale', label: 'Rochdale' },
  { value: 'Rotherham', label: 'Rotherham' },
  { value: 'Walthamstow', label: 'Walthamstow' },
  { value: 'Basingstoke', label: 'Basingstoke' },
  { value: 'Salford', label: 'Salford' },
  { value: 'Hounslow', label: 'Hounslow' },
  { value: 'Wembley', label: 'Wembley' },
  { value: 'Worcester', label: 'Worcester' },
  { value: 'Hammersmith', label: 'Hammersmith' },
  { value: 'Rayleigh', label: 'Rayleigh' },
  { value: 'Hemel Hempstead', label: 'Hemel Hempstead' },
  { value: 'Bath', label: 'Bath' },
  { value: 'Hayes', label: 'Hayes' },
  { value: 'Darlington', label: 'Darlington' },
  { value: 'Hove', label: 'Hove' },
  { value: 'Hastings', label: 'Hastings' },
  { value: 'Watford', label: 'Watford' },
  { value: 'Stevenage', label: 'Stevenage' },
  { value: 'Hartlepool', label: 'Hartlepool' },
  { value: 'Chester', label: 'Chester' },
  { value: 'Fulham', label: 'Fulham' },
  { value: 'Nuneaton', label: 'Nuneaton' },
  { value: 'Ealing', label: 'Ealing' },
  { value: 'Aylesbury', label: 'Aylesbury' },
  { value: 'Edmonton', label: 'Edmonton' },
  { value: 'Saint Albans', label: 'Saint Albans' },
  { value: 'Burnley', label: 'Burnley' },
  { value: 'Batley', label: 'Batley' },
  { value: 'Scunthorpe', label: 'Scunthorpe' },
  { value: 'Dudley', label: 'Dudley' },
  { value: 'Brixton', label: 'Brixton' },
  { value: 'Southall', label: 'Southall' },
  { value: 'Paisley', label: 'Paisley' },
  { value: 'Chatham', label: 'Chatham' },
  { value: 'East Ham', label: 'East Ham' },
  { value: 'Weston-super-Mare', label: 'Weston-super-Mare' },
  { value: 'Carlisle', label: 'Carlisle' },
  { value: 'South Shields', label: 'South Shields' },
  { value: 'East Kilbride', label: 'East Kilbride' },
  { value: 'Burton upon Trent', label: 'Burton upon Trent' },
  { value: 'Harrogate', label: 'Harrogate' },
  { value: 'Crewe', label: 'Crewe' },
  { value: 'Lowestoft', label: 'Lowestoft' },
  { value: 'Rugby', label: 'Rugby' },
  { value: 'Chingford', label: 'Chingford' },
  { value: 'Uxbridge', label: 'Uxbridge' },
  { value: 'Walsall', label: 'Walsall' },
  { value: 'Grays', label: 'Grays' },
  { value: 'Walton upon Thames', label: 'Walton upon Thames' },
  { value: 'Thornton Heath', label: 'Thornton Heath' },
  { value: 'Finchley', label: 'Finchley' },
  { value: 'Kensington', label: 'Kensington' },
  { value: 'Boston', label: 'Boston' },
  { value: 'Paignton', label: 'Paignton' },
  { value: 'Waterlooville', label: 'Waterlooville' },
  { value: 'Guiseley', label: 'Guiseley' },
  { value: 'Hornchurch', label: 'Hornchurch' },
  { value: 'Mitcham', label: 'Mitcham' },
  { value: 'Feltham', label: 'Feltham' },
  { value: 'Stourbridge', label: 'Stourbridge' },
  { value: 'Rochester', label: 'Rochester' },
  { value: 'Dewsbury', label: 'Dewsbury' },
  { value: 'Acton', label: 'Acton' },
  { value: 'Twickenham', label: 'Twickenham' },
  { value: 'Wrecsam', label: 'Wrecsam' },
  { value: 'Ellesmere Port', label: 'Ellesmere Port' },
  { value: 'Bangor', label: 'Bangor' },
  { value: 'Taunton', label: 'Taunton' },
  { value: 'Loughborough', label: 'Loughborough' },
  { value: 'Barking', label: 'Barking' },
  { value: 'Edgware', label: 'Edgware' },
  { value: 'Littlehampton', label: 'Littlehampton' },
  { value: 'Ruislip', label: 'Ruislip' },
  { value: 'Streatham', label: 'Streatham' },
  { value: 'Royal Tunbridge Wells', label: 'Royal Tunbridge Wells' },
  { value: 'Bebington', label: 'Bebington' },
  { value: 'Macclesfield', label: 'Macclesfield' },
  { value: 'Wellingborough', label: 'Wellingborough' },
  { value: 'Kettering', label: 'Kettering' },
  { value: 'Braintree', label: 'Braintree' },
  { value: 'Royal Leamington Spa', label: 'Royal Leamington Spa' },
  { value: 'Barrow in Furness', label: 'Barrow in Furness' },
  { value: 'Dunfermline', label: 'Dunfermline' },
  { value: 'Altrincham', label: 'Altrincham' },
  { value: 'Lancaster', label: 'Lancaster' },
  { value: 'Crosby', label: 'Crosby' },
  { value: 'Bootle', label: 'Bootle' },
  { value: 'Stratford', label: 'Stratford' },
  { value: 'Folkestone', label: 'Folkestone' },
  { value: 'Cumbernauld', label: 'Cumbernauld' },
  { value: 'Andover', label: 'Andover' },
  { value: 'Neath', label: 'Neath' },
  { value: 'Rowley Regis', label: 'Rowley Regis' },
  { value: 'Scarborough', label: 'Scarborough' },
  { value: 'Leith', label: 'Leith' },
  { value: 'Yeovil', label: 'Yeovil' },
  { value: 'Eltham', label: 'Eltham' },
  { value: 'Hampstead', label: 'Hampstead' },
  { value: 'Sutton in Ashfield', label: 'Sutton in Ashfield' },
  { value: 'Morden', label: 'Morden' },
  { value: 'Barnet', label: 'Barnet' },
  { value: 'Stretford', label: 'Stretford' },
  { value: 'Beckenham', label: 'Beckenham' },
  { value: 'Greenford', label: 'Greenford' },
  { value: 'Cheshunt', label: 'Cheshunt' },
  { value: 'Kirkby', label: 'Kirkby' },
  { value: 'Salisbury', label: 'Salisbury' },
  { value: 'Ashton', label: 'Ashton' },
  { value: 'Surbiton', label: 'Surbiton' },
  { value: 'Castleford', label: 'Castleford' },
  { value: 'Catford', label: 'Catford' },
  { value: 'Worksop', label: 'Worksop' },
  { value: 'Morley', label: 'Morley' },
  { value: 'Merthyr Tudful', label: 'Merthyr Tudful' },
  { value: 'Middleton', label: 'Middleton' },
  { value: 'Fleet', label: 'Fleet' },
  { value: 'Fareham', label: 'Fareham' },
  { value: 'Urmston', label: 'Urmston' },
  { value: 'Sutton', label: 'Sutton' },
  { value: 'Caerphilly', label: 'Caerphilly' },
  { value: 'Bridgwater', label: 'Bridgwater' },
  { value: 'Newbury', label: 'Newbury' },
  { value: 'Welling', label: 'Welling' },
  { value: 'Kingswood', label: 'Kingswood' },
  { value: 'Dunstable', label: 'Dunstable' },
  { value: 'Ramsgate', label: 'Ramsgate' },
  { value: 'Strood', label: 'Strood' },
  { value: 'Cleethorpes', label: 'Cleethorpes' },
  { value: 'Pinner', label: 'Pinner' },
  { value: 'Great Yarmouth', label: 'Great Yarmouth' },
  { value: 'Ilkeston', label: 'Ilkeston' },
  { value: 'Chorley', label: 'Chorley' },
  { value: 'Herne Bay', label: 'Herne Bay' },
  { value: 'Bishops Stortford', label: 'Bishops Stortford' },
  { value: 'Arnold', label: 'Arnold' },
  { value: 'Coalville', label: 'Coalville' },
  { value: 'Bletchley', label: 'Bletchley' },
  { value: 'Leighton Buzzard', label: 'Leighton Buzzard' },
  { value: 'Airdrie', label: 'Airdrie' },
  { value: 'Blyth', label: 'Blyth' },
  { value: 'Laindon', label: 'Laindon' },
  { value: 'Llanelli', label: 'Llanelli' },
  { value: 'Beeston', label: 'Beeston' },
  { value: 'Small Heath', label: 'Small Heath' },
  { value: 'Whitley Bay', label: 'Whitley Bay' },
  { value: 'Denton', label: 'Denton' },
  { value: 'West Bridgford', label: 'West Bridgford' },
  { value: 'Borehamwood', label: 'Borehamwood' },
  { value: 'Falkirk', label: 'Falkirk' },
  { value: 'Walkden', label: 'Walkden' },
  { value: 'Kenton', label: 'Kenton' },
  { value: 'Bridlington', label: 'Bridlington' },
  { value: 'Billingham', label: 'Billingham' },
  { value: 'Grantham', label: 'Grantham' },
  { value: 'North Shields', label: 'North Shields' },
  { value: 'Hitchin', label: 'Hitchin' },
  { value: 'Spalding', label: 'Spalding' },
  { value: 'Rainham', label: 'Rainham' },
  { value: 'Letchworth', label: 'Letchworth' },
  { value: 'Wickford', label: 'Wickford' },
  { value: 'Huyton', label: 'Huyton' },
  { value: 'Abingdon', label: 'Abingdon' },
  { value: 'Trowbridge', label: 'Trowbridge' },
  { value: 'Wigston Magna', label: 'Wigston Magna' },
  { value: 'Didcot', label: 'Didcot' },
  { value: 'Earley', label: 'Earley' },
  { value: 'Bexleyheath', label: 'Bexleyheath' },
  { value: 'Ecclesfield', label: 'Ecclesfield' },
  { value: 'Darwen', label: 'Darwen' },
  { value: 'Prestwich', label: 'Prestwich' },
  { value: 'Pontypridd', label: 'Pontypridd' },
  { value: 'Rutherglen', label: 'Rutherglen' },
  { value: 'Dover', label: 'Dover' },
  { value: 'Chichester', label: 'Chichester' },
  { value: 'Deal', label: 'Deal' },
  { value: 'Bicester', label: 'Bicester' },
  { value: 'Northolt', label: 'Northolt' },
  { value: 'Wishaw', label: 'Wishaw' },
  { value: 'Carshalton', label: 'Carshalton' },
  { value: 'Bulwell', label: 'Bulwell' },
  { value: 'Newtownards', label: 'Newtownards' },
  { value: 'Kendal', label: 'Kendal' },
  { value: 'Cramlington', label: 'Cramlington' },
  { value: 'Bromsgrove', label: 'Bromsgrove' },
  { value: 'Pont-y-pŵl', label: 'Pont-y-pŵl' },
  { value: 'Hanwell', label: 'Hanwell' },
  { value: 'Frome', label: 'Frome' },
  { value: 'Wood Green', label: 'Wood Green' },
  { value: 'Darlaston', label: 'Darlaston' },
  { value: 'Ashington', label: 'Ashington' },
  { value: 'Longton', label: 'Longton' },
  { value: 'Melton Mowbray', label: 'Melton Mowbray' },
  { value: 'Aldridge', label: 'Aldridge' },
  { value: 'Farnworth', label: 'Farnworth' },
  { value: 'Highbury', label: 'Highbury' },
  { value: 'Cheadle Hulme', label: 'Cheadle Hulme' },
  { value: 'Newton Aycliffe', label: 'Newton Aycliffe' },
  { value: 'Bournville', label: 'Bournville' },
  { value: 'Shenley Brook End', label: 'Shenley Brook End' },
  { value: 'Consett', label: 'Consett' },
  { value: 'Coulsdon', label: 'Coulsdon' },
  { value: 'Bilston', label: 'Bilston' },
  { value: 'Wellington', label: 'Wellington' },
  { value: 'Bishop Auckland', label: 'Bishop Auckland' },
  { value: 'Longbridge', label: 'Longbridge' },
  { value: 'Bloxwich', label: 'Bloxwich' },
  { value: 'Upminster', label: 'Upminster' },
  { value: 'Rhyl', label: 'Rhyl' },
  { value: 'Droitwich', label: 'Droitwich' },
  { value: 'Hindley', label: 'Hindley' },
  { value: 'Westhoughton', label: 'Westhoughton' },
  { value: 'Broadstairs', label: 'Broadstairs' },
];
