services:
  postgres:
    image: postgres:15
    container_name: mcommall-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Nov52002#
      POSTGRES_DB: mcom_mall
    ports:
      - '5432:5432'
    volumes:
      - mcommall-pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  mcommall-pgdata:
