// src/hooks/useGiftCardTemplates.ts

import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import api from '@/service/api'; // Assuming 'api' is your pre-configured Axios instance

// ## 1. Type Definitions

/**
 * Represents a gift card template as returned by the API.
 */
export interface GiftCardTemplate {
  id: string; // UUID
  name: string;
  description?: string;
  imageUrl?: string;
  fixedAmounts: number[];
  allowCustomAmount: boolean;
  minCustomAmount?: number;
  maxCustomAmount?: number;
  // Add other properties like createdAt, updatedAt if they exist in the API response
}

/**
 * Data Transfer Object (DTO) for creating a new gift card template.
 * The 'id' is omitted as it's generated by the server.
 */
export type CreateGiftCardTemplateDto = Omit<GiftCardTemplate, 'id'>;

/**
 * Data Transfer Object (DTO) for updating an existing gift card template.
 * All fields are optional to allow partial updates.
 */
export type UpdateGiftCardTemplateDto = Partial<CreateGiftCardTemplateDto>;

// ## 2. API Service Functions

const BASE_URL = '/merchant/gift-cards/templates';

/**
 * Fetches all gift card templates for the authenticated owner.
 * Corresponds to: GET /api/merchant/gift-cards/templates
 */
const fetchTemplates = async (): Promise<GiftCardTemplate[]> => {
  const { data } = await api.get<GiftCardTemplate[]>(BASE_URL);
  return data;
};

/**
 * Creates a new gift card template.
 * Corresponds to: POST /api/merchant/gift-cards/templates
 */
const createTemplate = async (
  templateData: CreateGiftCardTemplateDto
): Promise<GiftCardTemplate> => {
  const { data } = await api.post<GiftCardTemplate>(BASE_URL, templateData);
  return data;
};

/**
 * Updates an existing gift card template by its ID.
 * Corresponds to: PUT /api/merchant/gift-cards/templates/{id}
 */
const updateTemplate = async ({
  id,
  ...templateData
}: UpdateGiftCardTemplateDto & { id: string }): Promise<GiftCardTemplate> => {
  const { data } = await api.put<GiftCardTemplate>(
    `${BASE_URL}/${id}`,
    templateData
  );
  return data;
};

/**
 * Deletes a gift card template by its ID.
 * Corresponds to: DELETE /api/merchant/gift-cards/templates/{id}
 */
const deleteTemplate = async (id: string): Promise<void> => {
  await api.delete(`${BASE_URL}/${id}`);
};

// ## 3. React Query Custom Hooks

/**
 * Hook to fetch all gift card templates for the merchant.
 */
export const useGetGiftCardTemplates = () => {
  return useQuery<GiftCardTemplate[], Error>({
    queryKey: ['giftCardTemplates'],
    queryFn: fetchTemplates,
  });
};

/**
 * Hook to create a new gift card template.
 * Invalidates the template list query on success to refetch the latest data.
 */
export const useCreateGiftCardTemplate = () => {
  const queryClient = useQueryClient();
  return useMutation<GiftCardTemplate, Error, CreateGiftCardTemplateDto>({
    mutationFn: createTemplate,
    onSuccess: () => {
      // When a new template is created, invalidate the query for the list of templates
      // to trigger a refetch and update the UI.
      queryClient.invalidateQueries({ queryKey: ['giftCardTemplates'] });
    },
  });
};

/**
 * Hook to update an existing gift card template.
 * Invalidates the template list query on success.
 */
export const useUpdateGiftCardTemplate = () => {
  const queryClient = useQueryClient();
  return useMutation<
    GiftCardTemplate,
    Error,
    UpdateGiftCardTemplateDto & { id: string }
  >({
    mutationFn: updateTemplate,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['giftCardTemplates'] });
      // You could also invalidate a specific template query if you had one, e.g.:
      // queryClient.invalidateQueries({ queryKey: ['giftCardTemplates', data.id] });
    },
  });
};

/**
 * Hook to delete a gift card template.
 * Invalidates the template list query on success.
 */
export const useDeleteGiftCardTemplate = () => {
  const queryClient = useQueryClient();
  return useMutation<void, Error, string>({
    mutationFn: deleteTemplate,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['giftCardTemplates'] });
    },
  });
};