export type PromotionTypeTag = 'flash' | 'daily' | 'borough' | 'nearby' | 'seasonal' | 'high_street';

export interface PromotionItem {
  id: string;
  title: string;
  businessName: string;
  benefitValue: string;
  description: string;
  longDescription: string;
  locationTag?: string;
  borough?: string;
  distance?: string;
  expiryText: string;
  promotionType: PromotionTypeTag;
  image: string;
  badgeIcon: string;
  isUrgent?: boolean;
  isHot?: boolean;
  termsAndConditions?: string;
  qrCode?: string;
  redeemCode?: string;
  usageLimit?: number;
  usageCount?: number;
  discountValue?: string;
  campaignName?: string;
  unlockCondition?: string;
  unlockRewardDescription?: string;
  isUnlocked?: boolean;
  unlockProgress?: number;
  unlockTarget?: number;
}

export type PromotionsTab = 'all' | 'nearby' | 'flash' | 'borough' | 'saved' | 'expiring';

export const PROMOTIONS_MOCK_DATA: Record<string, PromotionItem> = {
  /* ===== FLASH DEALS ===== */
  "flash-1": {
    id: "flash-1",
    title: "50% Off All Burgers",
    businessName: "Grill House NYC",
    benefitValue: "50% OFF",
    description: "Massive flash sale on all gourmet burgers. Limited to first 50 customers!",
    longDescription: "Today only! Get 50% off any gourmet burger at Grill House NYC. Choose from 12 signature burgers including the classic American, spicy jalapeño, and truffle mushroom. Valid for dine-in and takeaway. First 50 customers only — once they're gone, they're gone!",
    locationTag: "Manhattan - 5th Ave",
    borough: "Manhattan",
    distance: "0.3 km",
    expiryText: "Ends in 2h 15m",
    promotionType: "flash",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=600",
    badgeIcon: "flash_on",
    isUrgent: true,
    isHot: true,
    termsAndConditions: "Valid today only. First 50 customers. Cannot be combined with other offers. Dine-in and takeaway.",
    usageLimit: 50,
    usageCount: 32,
    discountValue: "50%",
    redeemCode: "BURGER50",
  },
  "flash-2": {
    id: "flash-2",
    title: "Buy 1 Get 1 Free Coffee",
    businessName: "Brew & Co.",
    benefitValue: "BOGO Free",
    description: "Grab a friend! Buy any specialty coffee and get a second one absolutely free.",
    longDescription: "Flash deal alert! Buy any handcrafted specialty coffee at Brew & Co. and get a second one free. Choose from our full range including flat whites, cold brews, and seasonal specials. Offer valid for the next 3 hours only.",
    locationTag: "Brooklyn - Downtown",
    borough: "Brooklyn",
    distance: "0.8 km",
    expiryText: "Ends in 3h 00m",
    promotionType: "flash",
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&q=80&w=600",
    badgeIcon: "local_cafe",
    isUrgent: true,
    isHot: true,
    termsAndConditions: "Valid for next 3 hours. Second coffee of equal or lesser value. One per customer.",
    discountValue: "BOGO",
    redeemCode: "BOGOCOFFEE",
  },
  "flash-3": {
    id: "flash-3",
    title: "30% Off Sushi Platters",
    businessName: "Sakura Sushi Bar",
    benefitValue: "30% OFF",
    description: "Premium sushi platters at a fraction of the price. Lunchtime flash sale!",
    longDescription: "Sakura Sushi Bar's lunchtime flash sale is here! Enjoy 30% off all signature sushi platters including the Rainbow Roll Platter, Chef's Special Omakase, and the Sakura Deluxe. Fresh ingredients, masterfully prepared. Order now before time runs out!",
    locationTag: "Manhattan - Midtown",
    borough: "Manhattan",
    distance: "1.2 km",
    expiryText: "Ends in 1h 45m",
    promotionType: "flash",
    image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&q=80&w=600",
    badgeIcon: "restaurant",
    isUrgent: true,
    discountValue: "30%",
  },

  /* ===== DAILY DEALS ===== */
  "daily-1": {
    id: "daily-1",
    title: "20% Off All Apparel",
    businessName: "Urban Threads",
    benefitValue: "20% OFF",
    description: "Today's daily deal — refresh your wardrobe with 20% off everything in-store.",
    longDescription: "Today only: enjoy 20% off all apparel at Urban Threads. From casual streetwear to evening elegance, find your perfect look at a discount. Includes men's, women's, and accessories sections. Full-price items only. Visit us on Level 2.",
    locationTag: "MCOM Mall - Level 2",
    borough: "Queens",
    distance: "2.5 km",
    expiryText: "Ends today at midnight",
    promotionType: "daily",
    image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&q=80&w=600",
    badgeIcon: "checkroom",
    termsAndConditions: "Valid today only. Full-price items. Cannot be combined with other discounts.",
    discountValue: "20%",
  },
  "daily-2": {
    id: "daily-2",
    title: "Free Dessert with Main Course",
    businessName: "The Italian Kitchen",
    benefitValue: "Free Dessert",
    description: "Today's special: order any main course and receive a complimentary dessert.",
    longDescription: "Today's daily deal at The Italian Kitchen! Order any main course from our authentic Italian menu and enjoy a complimentary dessert of your choice. Choose from tiramisu, panna cotta, or gelato. Buon appetito!",
    locationTag: "Brooklyn - Heights",
    borough: "Brooklyn",
    distance: "1.8 km",
    expiryText: "Ends today at 10 PM",
    promotionType: "daily",
    image: "https://images.unsplash.com/photo-1551218808-94e220e084d2?auto=format&fit=crop&q=80&w=600",
    badgeIcon: "restaurant",
    termsAndConditions: "One dessert per main course. Dine-in only. Valid today only.",
    discountValue: "Free Dessert",
  },
  "daily-3": {
    id: "daily-3",
    title: "25% Off Gym Day Pass",
    businessName: "Peak Performance Gym",
    benefitValue: "25% OFF",
    description: "Sweat it out today with a discounted day pass at Peak Performance Gym.",
    longDescription: "Today's daily deal — 25% off all day passes at Peak Performance Gym! Access state-of-the-art equipment, group classes, sauna, and steam room. No membership required. Just show this offer at reception.",
    locationTag: "MCOM Mall - Level 3",
    borough: "Manhattan",
    distance: "0.5 km",
    expiryText: "Ends today at 9 PM",
    promotionType: "daily",
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=600",
    badgeIcon: "fitness_center",
    termsAndConditions: "Valid for day passes only. Cannot be combined with membership offers.",
    discountValue: "25%",
    unlockCondition: "Check in at the gym 5 times this month",
    unlockRewardDescription: "Free personal training session",
    unlockProgress: 3,
    unlockTarget: 5,
  },

  /* ===== BOROUGH PROMOTIONS ===== */
  "borough-1": {
    id: "borough-1",
    title: "Manhattan Lunch Specials",
    businessName: "Multiple Businesses",
    benefitValue: "Up to 40% OFF",
    description: "Explore Manhattan's best lunch deals. Participating restaurants offering exclusive discounts.",
    longDescription: "Manhattan Borough Promotion! We've partnered with 15+ restaurants across Manhattan to bring you exclusive lunch specials. From华尔街 delis to Midtown bistros, enjoy up to 40% off your midday meal. Flash your MCOM app at checkout.",
    locationTag: "Manhattan",
    borough: "Manhattan",
    expiryText: "Expires in 7 days",
    promotionType: "borough",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&q=80&w=600",
    badgeIcon: "location_city",
    campaignName: "Manhattan Lunch Week",
    discountValue: "Up to 40%",
  },
  "borough-2": {
    id: "borough-2",
    title: "Brooklyn Artisan Market",
    businessName: "Brooklyn Collective",
    benefitValue: "Buy 2 Get 1 Free",
    description: "Support local Brooklyn artisans! Buy 2 products, get 1 free at participating stalls.",
    longDescription: "Brooklyn Borough Promotion! The Brooklyn Artisan Market is a curated collection of local makers, bakers, and creators. Buy any 2 products from participating stalls and get a third item free. From handmade jewelry to organic baked goods — discover Brooklyn's best.",
    locationTag: "Brooklyn",
    borough: "Brooklyn",
    expiryText: "Expires in 14 days",
    promotionType: "borough",
    image: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?auto=format&fit=crop&q=80&w=600",
    badgeIcon: "storefront",
    campaignName: "Brooklyn Artisan Week",
    discountValue: "B2G1 Free",
  },
  "borough-3": {
    id: "borough-3",
    title: "Queens Family Fun Pass",
    businessName: "Queens Parks & Rec",
    benefitValue: "15% OFF",
    description: "Family-friendly activities across Queens at a discount. Perfect for weekends!",
    longDescription: "Queens Borough Promotion! Get 15% off entry to family-friendly attractions across Queens including the Queens Museum, Hall of Science, NYSCI, and the Queens Zoo. Pass is valid for up to 4 family members. Weekend fun starts here!",
    locationTag: "Queens",
    borough: "Queens",
    expiryText: "Expires in 30 days",
    promotionType: "borough",
    image: "https://images.unsplash.com/photo-1582552938357-32b906df40cb?auto=format&fit=crop&q=80&w=600",
    badgeIcon: "family_restroom",
    campaignName: "Queens Family Month",
    discountValue: "15%",
  },

  /* ===== NEARBY OFFERS ===== */
  "nearby-1": {
    id: "nearby-1",
    title: "10% Off Smoothie Bowls",
    businessName: "Tropical Oasis",
    benefitValue: "10% OFF",
    description: "Just around the corner! Cool down with a fresh smoothie bowl at a discount.",
    longDescription: "You're just steps away from Tropical Oasis! Stop by for 10% off any smoothie bowl or fresh juice. Our acai bowls, pitaya bowls, and green smoothies are made with organic ingredients. The perfect post-workout or midday refreshment.",
    locationTag: "0.1 km away",
    distance: "0.1 km",
    borough: "Manhattan",
    expiryText: "Expires in 5 days",
    promotionType: "nearby",
    image: "https://images.unsplash.com/photo-1505252585461-04db1eb84625?auto=format&fit=crop&q=80&w=600",
    badgeIcon: "spa",
    discountValue: "10%",
    unlockCondition: "Visit Tropical Oasis 3 times this week",
    unlockRewardDescription: "Free large smoothie after 3 visits",
    unlockProgress: 1,
    unlockTarget: 3,
  },
  "nearby-2": {
    id: "nearby-2",
    title: "Free Shoe Shine with Purchase",
    businessName: "Leather & Lace",
    benefitValue: "Free Shoe Shine",
    description: "Nearby luxury shoe boutique offering a complimentary shoe shine with any purchase.",
    longDescription: "Visit Leather & Lace, located just 0.3 km from you, and receive a complimentary premium shoe shine with any purchase. Our expert craftsmen will restore your leather shoes to their former glory. Browse our collection of Italian leather footwear while you wait.",
    locationTag: "0.3 km away",
    distance: "0.3 km",
    borough: "Manhattan",
    expiryText: "Expires in 3 days",
    promotionType: "nearby",
    image: "https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&q=80&w=600",
    badgeIcon: "clean_hands",
    discountValue: "Free Service",
  },
  "nearby-3": {
    id: "nearby-3",
    title: "20% Off Yoga Class",
    businessName: "Zenith Wellness Studio",
    benefitValue: "20% OFF",
    description: "A 5-minute walk away! Unwind with a discounted yoga session today.",
    longDescription: "Zenith Wellness Studio is just 0.5 km from your location! Enjoy 20% off any drop-in yoga class. Choose from Hatha, Vinyasa, or restorative Yin yoga. Mats and props provided. Beginners welcome! Breathe, stretch, and relax with us.",
    locationTag: "0.5 km away",
    distance: "0.5 km",
    borough: "Manhattan",
    expiryText: "Expires in 7 days",
    promotionType: "nearby",
    image: "https://images.unsplash.com/photo-1545205597-3d9d02c29597?auto=format&fit=crop&q=80&w=600",
    badgeIcon: "self_improvement",
    discountValue: "20%",
  },

  /* ===== SEASONAL PROMOTIONS ===== */
  "seasonal-1": {
    id: "seasonal-1",
    title: "Summer Festival Sale",
    businessName: "MCOM Mall",
    benefitValue: "Up to 60% OFF",
    description: "Summer is here! Massive seasonal sale across all participating stores.",
    longDescription: "The MCOM Summer Festival is here! Enjoy up to 60% off across 50+ participating stores including fashion, electronics, home goods, and dining. Plus, earn double points on every purchase during the festival period. Don't miss the biggest sale of the season!",
    locationTag: "All MCOM Locations",
    expiryText: "Expires Aug 31",
    promotionType: "seasonal",
    image: "https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?auto=format&fit=crop&q=80&w=600",
    badgeIcon: "wb_sunny",
    campaignName: "Summer Festival 2025",
    discountValue: "Up to 60%",
  },
  "seasonal-2": {
    id: "seasonal-2",
    title: "Back to School Bundle",
    businessName: "MCOM Mall",
    benefitValue: "15% OFF + Free Gift",
    description: "Get ready for school! Exclusive discounts on stationery, tech, and apparel.",
    longDescription: "Back to School at MCOM Mall! Get 15% off all school essentials including stationery, laptops, backpacks, and uniforms. Plus, receive a free MCOM tote bag with every purchase over $100. Participating stores include TechWorld, BookNook, and Campus Style.",
    locationTag: "All MCOM Locations",
    expiryText: "Expires Sep 15",
    promotionType: "seasonal",
    image: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=600",
    badgeIcon: "school",
    campaignName: "Back to School 2025",
    discountValue: "15% + Gift",
  },
  "seasonal-3": {
    id: "seasonal-3",
    title: "Holiday Gift Guide Deals",
    businessName: "MCOM Mall",
    benefitValue: "25% OFF Selected Items",
    description: "Spread the joy! Holiday-exclusive deals on gifts, decorations, and more.",
    longDescription: "The MCOM Holiday Gift Guide is live! Discover curated gift ideas for everyone on your list and save 25% on selected items. From luxury gifts to stocking stuffers, find the perfect presents at participating stores. Free gift wrapping available!",
    locationTag: "All MCOM Locations",
    expiryText: "Expires Dec 31",
    promotionType: "seasonal",
    image: "https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&q=80&w=600",
    badgeIcon: "celebration",
    campaignName: "Holiday Gift Guide 2025",
    discountValue: "25%",
  },

  /* ===== HIGH STREET PROMOTIONS ===== */
  "highstreet-1": {
    id: "highstreet-1",
    title: "5th Avenue Fashion Week",
    businessName: "5th Avenue Collective",
    benefitValue: "30% OFF + Perks",
    description: "Major brand collaboration! Designer stores on 5th Ave offering exclusive discounts.",
    longDescription: "The 5th Avenue Fashion Week promotion is here! Partner brands including Luxe Couture, Pristine, Velvet & Co., and Stellar Style are offering 30% off full-price items plus complimentary champagne and personal styling sessions. Experience premium shopping at its finest.",
    locationTag: "5th Avenue, Manhattan",
    borough: "Manhattan",
    expiryText: "Expires in 10 days",
    promotionType: "high_street",
    image: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?auto=format&fit=crop&q=80&w=600",
    badgeIcon: "diamond",
    campaignName: "5th Ave Fashion Week",
    discountValue: "30% + Perks",
  },
  "highstreet-2": {
    id: "highstreet-2",
    title: "Brooklyn Tech Hub Deal",
    businessName: "Brooklyn Tech Alliance",
    benefitValue: "20% OFF Electronics",
    description: "Tech lovers unite! Major electronics retailers in Brooklyn's Tech Hub offering 20% off.",
    longDescription: "Brooklyn Tech Hub High Street Promotion! Participating electronics retailers including Digital Oasis, Gadget Garage, and Compute Hub are offering 20% off all electronics and accessories. From laptops to smart home devices, upgrade your tech game today.",
    locationTag: "Brooklyn Tech Hub",
    borough: "Brooklyn",
    expiryText: "Expires in 21 days",
    promotionType: "high_street",
    image: "https://images.unsplash.com/photo-1468495244123-6c6c332eeece?auto=format&fit=crop&q=80&w=600",
    badgeIcon: "smartphone",
    campaignName: "Brooklyn Tech Month",
    discountValue: "20%",
  },
};

export const PROMOTION_TYPE_CONFIG: Record<PromotionTypeTag, { label: string; bg: string; text: string }> = {
  flash: { label: 'Flash Deal', bg: 'bg-rose-100', text: 'text-rose-700' },
  daily: { label: 'Daily Deal', bg: 'bg-sky-100', text: 'text-sky-700' },
  borough: { label: 'Borough', bg: 'bg-amber-100', text: 'text-amber-700' },
  nearby: { label: 'Nearby', bg: 'bg-emerald-100', text: 'text-emerald-700' },
  seasonal: { label: 'Seasonal', bg: 'bg-purple-100', text: 'text-purple-700' },
  high_street: { label: 'High Street', bg: 'bg-indigo-100', text: 'text-indigo-700' },
};
