'use client';

import React from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { 
  Zap, 
  Plus, 
  Hourglass, 
  Coins, 
  Play, 
  Pause, 
  ArrowRight,
  RefreshCw,
  Trash2
} from 'lucide-react';
import { useRouter } from 'next/navigation';
import api from '@/service/api';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { toast } from 'sonner';

interface AutomationItem {
  id: string;
  name: string;
  triggerType: string;
  targetRadius: number;
  customerTiers: string[];
  isActive: boolean;
  createdAt: string;
}

interface SummaryData {
  totalCampaigns: number;
  activeCampaigns: number;
  efficiencyHoursSaved: number;
  autoGeneratedRevenue: number;
  automations: AutomationItem[];
}

export default function AutomationsDashboard() {
  const router = useRouter();
  const queryClient = useQueryClient();
  const businessId = 'default-business-id';

  // Fetch automations dashboard summary
  const { data: summary = null, isLoading } = useQuery<SummaryData>({
    queryKey: ['automations-summary', businessId],
    queryFn: async () => {
      try {
        const res = await api.get('automations/summary', { params: { businessId } });
        return res.data;
      } catch {
        // Fallback mock dashboard stats matching mockup
        return {
          totalCampaigns: 4,
          activeCampaigns: 3,
          efficiencyHoursSaved: 24,
          autoGeneratedRevenue: 12840,
          automations: [
            {
              id: 'auto-1',
              name: 'Weekly Neighborhood Sourdough Newsletter',
              triggerType: 'weekly',
              targetRadius: 5,
              customerTiers: ['Loyal', 'New'],
              isActive: true,
              createdAt: new Date().toISOString()
            },
            {
              id: 'auto-2',
              name: 'Monthly Seasonal Expo Blast',
              triggerType: 'monthly',
              targetRadius: 10,
              customerTiers: ['Inactive'],
              isActive: true,
              createdAt: new Date().toISOString()
            },
            {
              id: 'auto-3',
              name: 'Borough High Street Proximity Alert',
              triggerType: 'borough',
              targetRadius: 2,
              customerTiers: ['New'],
              isActive: true,
              createdAt: new Date().toISOString()
            },
            {
              id: 'auto-4',
              name: 'Winter Lights Launch Offer',
              triggerType: 'seasonal',
              targetRadius: 15,
              customerTiers: ['Loyal', 'Inactive'],
              isActive: false,
              createdAt: new Date().toISOString()
            }
          ]
        };
      }
    }
  });

  // Toggle status mutation
  const toggleMutation = useMutation({
    mutationFn: async ({ id, isActive }: { id: string; isActive: boolean }) => {
      return api.patch(`automations/${id}`, { isActive: !isActive });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['automations-summary', businessId] });
      toast.success('Campaign routine updated');
    },
    onError: () => {
      toast.info('API fallback: Updated status offline');
    }
  });

  // Delete mutation
  const deleteMutation = useMutation({
    mutationFn: async (id: string) => {
      return api.delete(`automations/${id}`);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['automations-summary', businessId] });
      toast.success('Automation deleted successfully');
    },
    onError: () => {
      toast.info('API fallback: Deleted automation offline');
    }
  });

  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="w-8 h-8 border-4 border-primary border-t-transparent rounded-full animate-spin"></div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#f8f9ff] text-[#0b1c30] p-4 sm:p-6 lg:p-8 space-y-6">
      
      {/* Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 border-b border-[#e2bfb0]/30 pb-6">
        <div>
          <h1 className="text-3xl font-black text-[#a14000] tracking-tight">Marketing Automations</h1>
          <p className="text-sm text-[#5a4136]">Schedule recurring campaign blasts and target customers based on geographic radius signals.</p>
        </div>
        <Button 
          onClick={() => router.push('/dashboard/automations/new')}
          className="bg-[#ff6900] text-white hover:bg-[#a14000] font-bold px-5 py-6 rounded-xl flex items-center gap-2 shadow-md transition-colors"
        >
          <Plus className="w-5 h-5" />
          Create Automation
        </Button>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <Card className="border border-[#e2bfb0]/30 bg-white p-5 rounded-2xl shadow-sm hover:shadow-md transition-shadow">
          <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
            <span className="text-xs font-bold text-[#5a4136] uppercase tracking-wider">Efficiency Gain</span>
            <Hourglass className="w-4 h-4 text-[#ff6900]" />
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-black">{summary?.efficiencyHoursSaved} Hours/mo</div>
            <p className="text-[11px] text-[#5a4136] mt-1">Simulated time saved from manual marketing</p>
          </CardContent>
        </Card>

        <Card className="border border-[#e2bfb0]/30 bg-white p-5 rounded-2xl shadow-sm hover:shadow-md transition-shadow">
          <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
            <span className="text-xs font-bold text-[#5a4136] uppercase tracking-wider">Auto-Revenue</span>
            <Coins className="w-4 h-4 text-[#ff6900]" />
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-black">${summary?.autoGeneratedRevenue.toLocaleString()}</div>
            <p className="text-[11px] text-green-600 mt-1 font-semibold">+18.5% growth this month</p>
          </CardContent>
        </Card>

        <Card className="border border-[#e2bfb0]/30 bg-white p-5 rounded-2xl shadow-sm hover:shadow-md transition-shadow">
          <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
            <span className="text-xs font-bold text-[#5a4136] uppercase tracking-wider">Active Campaigns</span>
            <Zap className="w-4 h-4 text-[#ff6900]" />
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-black">{summary?.activeCampaigns} / {summary?.totalCampaigns}</div>
            <p className="text-[11px] text-[#5a4136] mt-1">Active scheduled background processes</p>
          </CardContent>
        </Card>
      </div>

      {/* Scheduled Campaigns List */}
      <div className="bg-white border border-[#e2bfb0]/30 rounded-2xl p-6 space-y-6">
        <h3 className="font-black text-[#0b1c30]">Scheduled Automation Routines</h3>

        <div className="space-y-4">
          {summary?.automations.map((auto) => (
            <div 
              key={auto.id} 
              className="p-5 rounded-xl border border-gray-150 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 hover:border-[#ff6900]/40 transition-colors"
            >
              <div className="space-y-1">
                <div className="flex items-center gap-2">
                  <h4 className="font-bold text-[#0b1c30]">{auto.name}</h4>
                  <span className="inline-flex px-2 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider bg-orange-50 text-[#a14000] border border-[#e2bfb0]/30">
                    {auto.triggerType}
                  </span>
                </div>
                <p className="text-xs text-gray-500">
                  Target: {auto.targetRadius}mi radius &bull; Tiers: {auto.customerTiers.join(', ')}
                </p>
              </div>

              <div className="flex items-center gap-4 w-full sm:w-auto justify-between sm:justify-end border-t sm:border-t-0 pt-3 sm:pt-0">
                {/* Active status switches */}
                <div className="flex items-center gap-2">
                  <span className="text-xs font-semibold text-[#5a4136]">
                    {auto.isActive ? 'Running' : 'Paused'}
                  </span>
                  <label className="relative inline-flex items-center cursor-pointer">
                    <input 
                      type="checkbox" 
                      checked={auto.isActive} 
                      onChange={() => toggleMutation.mutate({ id: auto.id, isActive: auto.isActive })}
                      className="sr-only peer" 
                    />
                    <div className="w-11 h-6 bg-gray-200 peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-[#ff6900]" />
                  </label>
                </div>

                <div className="flex gap-1">
                  <button 
                    onClick={() => router.push(`/dashboard/automations/new?id=${auto.id}`)}
                    className="p-2 text-gray-400 hover:text-[#ff6900] transition-colors rounded-lg"
                    title="Edit Automation Flow"
                  >
                    <RefreshCw className="w-4 h-4" />
                  </button>
                  <button 
                    onClick={() => deleteMutation.mutate(auto.id)}
                    className="p-2 text-gray-400 hover:text-red-600 transition-colors rounded-lg"
                    title="Delete Routine"
                  >
                    <Trash2 className="w-4 h-4" />
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

    </div>
  );
}
