import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'McomMall',
  description: 'Generated by create next app',
};
export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="w-screen h-[calc(100vh-70px)] bg-white overflow-hidden pt-10">
      {children}
    </section>
  );
}
