export enum GroupType {
  MARKETING = 'MARKETING',
  ADVERTISING = 'ADVERTISING',
  NEARBY = 'NEARBY',
  HYPERLOCAL = 'HYPERLOCAL',
  NATIONAL = 'NATIONAL',
  GLOBAL = 'GLOBAL',
  SMART_MONEY = 'SMART_MONEY',
}
