export type AutomationTriggerType = 'weekly' | 'monthly' | 'seasonal' | 'borough';

export interface Automation {
    id: string;
    businessId: string;
    name: string;
    triggerType: AutomationTriggerType;
    targetRadius: number;
    customerTiers: string[];
    isActive: boolean;
    flowConfig?: unknown;
    createdAt: string;
    updatedAt: string;
}

export interface AutomationSummary {
    totalCampaigns: number;
    activeCampaigns: number;
    efficiencyHoursSaved: number;
    autoGeneratedRevenue: number;
    automations: Automation[];
}

export interface UpdateAutomationDto {
    name?: string;
    triggerType?: AutomationTriggerType;
    targetRadius?: number;
    customerTiers?: string[];
    isActive?: boolean;
    flowConfig?: unknown;
}
