import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import 'leaflet/dist/leaflet.css';
import './globals.css';
import ClientProviders from '@/components/client-provider';
import { Toaster } from 'sonner';
import Header from '@/components/Header';
import Auth from '@/components/auth';
import AuthInitializer from '@/components/AuthInitializer';

const opensans = Open_Sans({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'McomMall',
  description: 'Generated by create next app',
};

import Script from 'next/script';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${opensans.variable} antialiased pt-16`}>
        <ClientProviders>
          <AuthInitializer>
            <Header />
            {/* <Auth /> */}
            {children}
          </AuthInitializer>
        </ClientProviders>
        <Toaster />
        <Script src="https://unpkg.com/jspdf@latest/dist/jspdf.umd.min.js" />
        <Script src="https://unpkg.com/jspdf-autotable@latest/dist/jspdf.plugin.autotable.js" />
      </body>
    </html>
  );
}
