import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Automation } from './entities/automation.entity';
import { CreateAutomationDto } from './dto/create-automation.dto';
import { UpdateAutomationDto } from './dto/update-automation.dto';

@Injectable()
export class AutomationsService {
  constructor(
    @InjectRepository(Automation)
    private readonly automationRepository: Repository<Automation>,
  ) {}

  async create(createDto: CreateAutomationDto): Promise<Automation> {
    const automation = this.automationRepository.create(createDto);
    return this.automationRepository.save(automation);
  }

  async findAllByBusiness(businessId: string): Promise<Automation[]> {
    return this.automationRepository.find({
      where: { businessId },
      order: { createdAt: 'DESC' },
    });
  }

  async findOne(id: string): Promise<Automation> {
    const automation = await this.automationRepository.findOne({
      where: { id },
    });
    if (!automation) {
      throw new NotFoundException(
        `Automation campaign flow with ID ${id} not found`,
      );
    }
    return automation;
  }

  async update(
    id: string,
    updateDto: UpdateAutomationDto,
  ): Promise<Automation> {
    const automation = await this.findOne(id);
    Object.assign(automation, updateDto);
    return this.automationRepository.save(automation);
  }

  async remove(id: string): Promise<void> {
    const automation = await this.findOne(id);
    await this.automationRepository.remove(automation);
  }

  async getDashboardSummary(businessId: string) {
    const automations = await this.findAllByBusiness(businessId);
    const totalCount = automations.length;
    const activeCount = automations.filter((a) => a.isActive).length;

    // Simulated dashboard stats
    const efficiencyHoursSaved = activeCount * 4 + 8; // Simulated: 4 hours per active workflow
    const autoGeneratedRevenue = activeCount * 1420 + 2460; // Simulated earnings

    return {
      totalCampaigns: totalCount,
      activeCampaigns: activeCount,
      efficiencyHoursSaved,
      autoGeneratedRevenue,
      automations,
    };
  }
}
