import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Automation, TriggerType } from './entities/automation.entity';
import { CreateAutomationDto } from './dto/create-automation.dto';
import { UpdateAutomationDto } from './dto/update-automation.dto';
import { PromotionParticipant } from '../promotion/entities/promotion-participant.entity';
import { Promotion } from '../promotion/entities/promotion.entity';
import { Business } from '../listings/entities/listing.entity';

const HOURS_PER_TRIGGER: Record<TriggerType, number> = {
  [TriggerType.WEEKLY]: 8,
  [TriggerType.MONTHLY]: 12,
  [TriggerType.SEASONAL]: 20,
  [TriggerType.BOROUGH]: 6,
};

@Injectable()
export class AutomationsService {
  constructor(
    @InjectRepository(Automation)
    private readonly automationRepository: Repository<Automation>,
    @InjectRepository(PromotionParticipant)
    private readonly participantRepository: Repository<PromotionParticipant>,
    @InjectRepository(Promotion)
    private readonly promotionRepository: Repository<Promotion>,
    @InjectRepository(Business)
    private readonly businessRepository: Repository<Business>,
  ) {}

  async create(createDto: CreateAutomationDto): Promise<Automation> {
    const automation = this.automationRepository.create(createDto);
    return this.automationRepository.save(automation);
  }

  async findAllByBusiness(businessId: string): Promise<Automation[]> {
    return this.automationRepository.find({
      where: { businessId },
      order: { createdAt: 'DESC' },
    });
  }

  async findOne(id: string): Promise<Automation> {
    const automation = await this.automationRepository.findOne({
      where: { id },
    });
    if (!automation) {
      throw new NotFoundException(
        `Automation campaign flow with ID ${id} not found`,
      );
    }
    return automation;
  }

  async update(
    id: string,
    updateDto: UpdateAutomationDto,
  ): Promise<Automation> {
    const automation = await this.findOne(id);
    Object.assign(automation, updateDto);
    return this.automationRepository.save(automation);
  }

  async remove(id: string): Promise<void> {
    const automation = await this.findOne(id);
    await this.automationRepository.remove(automation);
  }

  async getDashboardSummary(businessId: string) {
    const automations = await this.findAllByBusiness(businessId);
    const totalCount = automations.length;
    const activeCount = automations.filter((a) => a.isActive).length;

    // Time saved derived from active automation trigger cadence
    const efficiencyHoursSaved = automations
      .filter((a) => a.isActive)
      .reduce((sum, a) => sum + (HOURS_PER_TRIGGER[a.triggerType] ?? 8), 0);

    // Auto-generated revenue derived from promotion participants whose
    // promotions belong to this business (points earned -> spend conversion).
    const promotionRevenueRaw = await this.participantRepository
      .createQueryBuilder('participant')
      .leftJoin('participant.promotion', 'promotion')
      .leftJoin('promotion.businesses', 'business')
      .select('COALESCE(SUM(participant.pointsEarned), 0)', 'sum')
      .where('business.id = :businessId', { businessId })
      .getRawOne();

    const pointsEarned = Number(promotionRevenueRaw?.sum ?? 0);
    // Assumes each point corresponds to roughly £0.10 of attributed spend
    const autoGeneratedRevenue = Math.round(pointsEarned * 0.1);

    return {
      totalCampaigns: totalCount,
      activeCampaigns: activeCount,
      efficiencyHoursSaved,
      autoGeneratedRevenue,
      automations,
    };
  }
}
