export const businessCategories = [
  {
    name: 'Hospitality',
    subCategories: [
      { name: 'Restaurants' },
      { name: 'Cafés / Coffee Shops' },
      { name: 'Takeaways / Delivery' },
      { name: 'Bakeries' },
      { name: 'Bars & Pubs' },
      { name: 'Breweries, Wineries & Distilleries' },
      { name: 'Catering Services' },
      { name: 'Dessert Shops' },
    ],
  },
  {
    name: 'Shopping & Retail',
    subCategories: [
      { name: 'Clothing & Fashion' },
      { name: 'Beauty & Cosmetics' },
      { name: 'Home & Garden' },
      { name: 'Electronics & Appliances' },
      { name: 'Books, Stationery & Gifts' },
      { name: 'Health Food / Organic' },
      { name: 'Pet Supplies' },
      { name: 'Toys & Hobbies' },
    ],
  },
  {
    name: 'Trades & Home Services',
    subCategories: [
      { name: 'Plumbing & Heating' },
      { name: 'Electrical Services' },
      { name: 'Builders & Construction' },
      { name: 'Carpentry & Joinery' },
      { name: 'Roofing & Guttering' },
      { name: 'Flooring & Tiling' },
      { name: 'Cleaning Services' },
      { name: 'Gardening & Landscaping' },
      { name: 'Pest Control' },
      { name: 'Locksmith & Security' },
      { name: 'Handyman Services' },
      { name: 'Decorators (Painters, Wallpapering)' },
    ],
  },
  {
    name: 'Beauty & Wellness',
    subCategories: [
      { name: 'Hairdressers & Barbers' },
      { name: 'Nail Salons' },
      { name: 'Beauty Salons' },
      { name: 'Spas & Wellness Centres' },
      { name: 'Massage Therapists' },
      { name: 'Tattoo & Piercing' },
      { name: 'Skincare Clinics' },
      { name: 'Tanning (Spray, Beds)' },
    ],
  },
  {
    name: 'Health & Medical',
    subCategories: [
      { name: 'General Practitioners (GP)' },
      { name: 'Dentists' },
      { name: 'Opticians' },
      { name: 'Physiotherapists' },
      { name: 'Massage Therapy' },
      { name: 'Counselling & Mental Health' },
      { name: 'Chiropractors' },
      { name: 'Diagnostic Services' },
      { name: 'Hospitals & Clinics' },
      { name: 'Weight Loss & Nutrition' },
    ],
  },
  {
    name: 'Others',
    subCategories: [
      { name: 'Property & Real Estate' },
      { name: 'Fitness & Sports' },
      { name: 'Automotive & Transport' },
      { name: 'Pets & Animal Services' },
      { name: 'Accommodation & Travel' },
      { name: 'Manufacturing & Industrial' },
      { name: 'Non-Profit & Community' },
      { name: 'Education & Training' },
      { name: 'Arts, Entertainment & Events' },
      { name: 'Media, Marketing & Professional Services' },
      { name: 'Hospitality (?)' },
    ],
  },
];
