import asyncio
from playwright.async_api import async_playwright

async def run():
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        context = await browser.new_context(viewport={'width': 1280, 'height': 800})
        page = await context.new_page()

        try:
            # Set auth cookies
            await context.add_cookies([
                {'name': 'access', 'value': 'token', 'domain': 'localhost', 'path': '/'},
                {'name': 'userRole', 'value': 'admin', 'domain': 'localhost', 'path': '/'}
            ])

            print("Verifying Service Templates...")
            await page.goto("http://localhost:3000/admin/templates/services")
            await page.wait_for_load_state("networkidle")

            # Target by name attribute which is generated by useFieldArray
            # Name should be "packages.0.name"
            pkg_name_input = page.locator('input[name="packages.0.name"]')
            await pkg_name_input.wait_for(state="visible", timeout=10000)

            # Verify the value is "Basic Clean"
            value = await pkg_name_input.input_value()
            if value != "Basic Clean":
                raise Exception(f"Expected 'Basic Clean', got '{value}'")
            print("Found 'Basic Clean' package input.")

            # Check Add Package button
            await page.get_by_role("button", name="Add Package").click()
            print("Clicked Add Package.")

            print("Verifying Compliance...")
            await page.goto("http://localhost:3000/admin/compliance")
            # Text is "Compliance & Policy"
            await page.wait_for_selector("text=Compliance & Policy", timeout=10000)

            await page.get_by_role("tab", name="Platform Rules").click()
            await page.get_by_role("tab", name="Legal Documents").click()
            print("Compliance tabs working.")

            print("Verifying Quality Assurance...")
            await page.goto("http://localhost:3000/admin/quality")
            # Text is "Quality Assurance"
            await page.wait_for_selector("text=Quality Assurance", timeout=10000)
            # Text is "Mystery Shoppers" or "Mystery Shopper Missions"
            await page.wait_for_selector("text=Mystery Shopper Missions", timeout=10000)
            print("Quality Assurance page loaded.")

            print("Verifying Training Hub...")
            await page.goto("http://localhost:3000/admin/training")
            # Text is "Training Hub"
            await page.wait_for_selector("text=Training Hub", timeout=10000)
            # Text is "Courses" (tab or content)
            await page.wait_for_selector("text=Seller Onboarding 101", timeout=10000)
            print("Training Hub page loaded.")

            print("Verifying Product Integration...")
            await page.goto("http://localhost:3000/admin/products")
            await page.wait_for_load_state("networkidle")
            print("Products page loaded.")

            print("All verifications passed successfully!")

        except Exception as e:
            print(f"Verification failed: {e}")
            await page.screenshot(path="verification_failure_v2.png")
            print("Screenshot saved to verification_failure_v2.png")
            raise e
        finally:
            await browser.close()

if __name__ == "__main__":
    asyncio.run(run())
