export enum ActivityTaskType {
  CREATE_BUSINESS = 'CREATE_BUSINESS',
  IMPORT_CONTACTS = 'IMPORT_CONTACTS',
  ADD_PRODUCT_SERVICE = 'ADD_PRODUCT_SERVICE',
  LIST_BARTER_OFFER = 'LIST_BARTER_OFFER',
  CONNECT_BUSINESS = 'CONNECT_BUSINESS',
  CREATE_PROMOTION = 'CREATE_PROMOTION',
  CREATE_COUPON = 'CREATE_COUPON',
  PAY_FOR_TIER = 'PAY_FOR_TIER',
  OTHER = 'OTHER',
}

export enum ActivityTimerType {
  TRIAL = 'TRIAL',
  GENERAL = 'GENERAL',
  BOTH = 'BOTH',
}