export enum ExchangeHistoryAction {
  ITEM_CREATED = 'ITEM_CREATED',
  ITEM_UPDATED = 'ITEM_UPDATED',
  ITEM_REMOVED = 'ITEM_REMOVED',
  PROPOSAL_CREATED = 'PROPOSAL_CREATED',
  PROPOSAL_ACCEPTED = 'PROPOSAL_ACCEPTED',
  PROPOSAL_REJECTED = 'PROPOSAL_REJECTED',
  PROPOSAL_CANCELED = 'PROPOSAL_CANCELED',
  TRADE_COMPLETED = 'TRADE_COMPLETED',
}