export enum PromotionType {
  MULTIPLIER = 'MULTIPLIER',
  BONUS_POINTS = 'BONUS_POINTS',
}

export enum PromotionScope {
  ALL_LISTINGS = 'ALL_LISTINGS',
  SPECIFIC_LISTINGS = 'SPECIFIC_LISTINGS',
  ALL_PRODUCTS = 'ALL_PRODUCTS',
  SPECIFIC_PRODUCTS = 'SPECIFIC_PRODUCTS',
}
